### ISSUE TITLE
Remove table-stripe and table-stroke classes

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#6531]
Remove table-stripe and table-stroke classes in theme.css. See #6505.

**Comment by arschmitz** [comment]
This already was fixed and landed on 1.5-dev

**Comment by jaspermdegroot** [comment]
Re-opening because I still see those styles in the theme CSS

**Comment by apsdehal** [comment]
Fixed in 1.5-dev.
