### ISSUE TITLE
Tabs not rendered properly when loaded from another file

### ISSUE THREAD

**Issue by amasniko** [jquery/jquery-mobile#7725]
The application consists of two separate files, and the second file contains tabs (data-role=tabs). The tab contents are local (not loaded through Ajax) and referenced from the navbar links using "#id" notation. The first file contains a link to the file with local tabs. The second file is not rendered correctly because the tab content is ot recognised as local. At one point the code check if the link is local (isLocal function) which effectively Compares the URLs before the fragment part of the link and the current page ("location"). But at that point the "location" has not yet been updated (still points to the first page) and the link is mistankenly detected as non-local.

You can find the code for the first page at http://jsbin.com/huvoraba/146 and the second at http://jsbin.com/huvoraba/145. The first page also contains tabs just to prove that they do render correctly when defined in the same file.

Note that it does not properly work on jsbin site (it does not appear to load the secon page using Ajax mechanism) abd you ill have to copy the files locally.

**Comment by arschmitz** [comment]
This is fixed in 1.5-dev closing.

**Comment by amasniko** [comment]
Sorry, but it appears the original problem is still present. If you try link from gabrielschulhof http://fiddle.jshell.net/nc6j3ez1/3/show/light/ and click on "Page 2" there, the content from both tabs will be displayed. As I mentioned earlier, "isLocal" function, now at line 14209, fails to identify the anchor as local. I have not debuged the simplified test case, but in my application it fails here:

	return anchor.hash.length > 1 &&
		decodeURIComponent( anchor.href.replace( rhash, "" ) ) ===
			decodeURIComponent( location.href.replace( rhash, "" ) );

At this point "anchor" has the URL of the new page with "#" suffix identifying the local tab, but "location" has not changed yet (still refers to the first page) and the comparison fails.
